/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder */

#ifndef _Included_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
#define _Included_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
 * Method:    open
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
 * Method:    encode
 * Signature: (I[SII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder_encode
  (JNIEnv *, jobject, jint, jshortArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
 * Method:    encodeWithBitRate
 * Signature: (I[SII[BII)I
 */
JNIEXPORT jint JNICALL Java_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder_encodeWithBitRate
  (JNIEnv *, jobject, jint, jshortArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
 * Method:    reset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder_reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
 * Method:    setBitRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder_setBitRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
 * Method:    setSampleRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder_setSampleRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
 * Method:    setFrameTime
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder_setFrameTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder
 * Method:    enableFEC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_reve_audio_libraries_dlls_codec_opus_OPUSEncoder_enableFEC
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
